### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by aloon** [ahoy-jon/example-scribe-client-server-scala#1]
when I execute:

```
$ ./sbt run
```

I have this error:

```
~/Documents/Projects/example-scribe-client-server-scala doesn't appear to be an sbt project.
If you want to start sbt anyway, run:
  ./sbt -sbt-create
```

independently my problem is that I don't know the dependencies
I would be nice if the project had build.sbt

Thanks

**Comment by ahoy-jon** [comment]
I am sorry, it was forgotten in the last commit. 

You can check out : 

https://github.com/ahoy-jon/example-scribe-client-server-scala/commit/49f5fb0e60c85ac042cef67e8ead499e81f5d469

**Comment by aloon** [comment]
perfect, thanks a lot
